language: elixir

elixir:
  - 1.10
  - 1.9

otp_release:
  - '22.3'

before_script:
  - mix compile –warnings-as-errors
  - mix credo --strict
  - if [[ "$TRAVIS_ELIXIR_VERSION" =~ "1.10" ]]; then mix format mix.exs "{config,clients,games,lib,test}/**/*.{ex,exs}" --check-formatted; fi

script: mix test --include large --include fuzz --exclude gnuplot --exclude bullet

cache:
  directories:
  - deps