language: elixir

elixir:
  - 1.9
  - 1.8
  - 1.7
  - 1.6

otp_release:
  - '20.0'

before_script:
  - mix compile –warnings-as-errors
  - mix credo --strict
  - if [[ "$TRAVIS_ELIXIR_VERSION" =~ "1.9" ]]; then mix format mix.exs "lib/**/*.{ex,exs}" "test/**/*.{ex,exs}" --check-formatted; fi

script: mix test --include large --include fuzz --exclude gnuplot --exclude bullet
