language: elixir

elixir:
  - 1.8.2
  - 1.8.1
  - 1.7
  - 1.6

otp_release:
  - '20.0'

before_script:
  - mix compile –warnings-as-errors
  - mix credo --strict
  - if [[ "$TRAVIS_ELIXIR_VERSION" =~ "1.8" ]]; then mix format mix.exs "lib/**/*.{ex,exs}" "test/**/*.{ex,exs}" --check-formatted; fi

script: mix test --include large --include slow --include fuzz --exclude gnuplot
