name: ci

on: [push, pull_request]

jobs:
  build:
    name: Elixir ${{matrix.elixir}} (Erlang/OTP ${{matrix.otp}})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ["23.3.4", "24.0"]
        elixir: ["v1.12.0-rc.1", "1.11.4", "1.10.4"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix credo --strict
      - name: "Check formatted?"
        run: mix format mix.exs "examples/*.exs" "lib/**/*.{ex,exs}" "test/**/*.exs" --check-formatted
        if: ${{ startsWith(matrix.elixir, '1.11') }}
      - run: mix test --include large --include fuzz --exclude gnuplot --exclude bullet
